#Minecraft server properties
#Fri Apr 10 23:12:23 CST 2026
accepts-transfers=false
allow-flight=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=hard
enable-code-of-conduct=false
enable-jmx-monitoring=true
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=YcMVXbfTdNDebeENpccTFPfDKli3T5gx3dmHxEaj
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=10000
max-players=20
max-tick-time=600000
max-world-size=29999984
motd=MT Network\nJava + Bedrock Vanilla+ SMP
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=-1
prevent-proxy-connections=false
query.port=11451
rate-limit=0
rcon.password=
rcon.port=11451
region-file-compression=lz4
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=11451
simulation-distance=4
spawn-protection=0
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=8
white-list=false
