name: Bug Report
description: Report a Bug.
title: "[Bug]: "
labels: ["bug"]
projects: []
'body':
  - 'attributes':
        'description': >
            Please make sure that the issue is not a duplicate or a question.
            If it's a duplicate, please react to the original issue with a
            thumbs up.
        'label': 'Prerequisites'
        'options':
          - 'label': >
                I have checked that this is not Mojang's issue.
            'required': true
          - 'label': >
                I have searched other issues and found no duplicates
            'required': true
          - 'label': >
                I want to report a bug and not asking a question.
            'required': true
          - 'label': >
                The bug can be repeated and not caused by network.
            'required': true
    'id': 'prerequisites'
    'type': 'checkboxes'
  - 'attributes':
        'description': 'Which platform are you using when the problem occurs?'
        'label': 'Platform'
        'options':
          - 'Windows Bedrock'
          - 'Windows Java'
          - 'Android Java'
          - 'Android Bedrock'
          - 'IOS Java'
          - 'IOS Bedrock'
          - 'Mac Java'
          - 'Custom (please mention in the description)'
    'id': 'os'
    'type': 'dropdown'
    'validations':
        'required': true
  - 'attributes':
        'description': 'What is the current version of MT Network?'
        'label': 'Server version'
    'id': 'versionsv'
    'type': 'input'
    'validations':
        'required': true
  - 'attributes':
        'description': 'What version of Minecraft are you using?'
        'label': 'Minecraft version'
    'id': 'versioncl'
    'type': 'input'
    'validations':
        'required': true
  - 'attributes':
        'description': >
            Please describe what you did.
        'label': 'Action'
    'id': 'failing_action'
    'type': 'textarea'
    'validations':
        'required': true
  - 'attributes':
        'description': >
            What did you expect to see?  Please add a description and/or
            screenshots, if applicable.
        'label': 'Expected result'
        'placeholder': >
            What did you expect to see?
    'id': 'expected'
    'type': 'textarea'
    'validations':
        'required': false
  - 'attributes':
        'description': >
            What happened instead?  Please add a description and/or screenshots,
            if applicable.
        'label': 'Actual result'
        'placeholder': >
            What did you see instead?
    'id': 'result'
    'type': 'textarea'
    'validations':
        'required': true
  - 'attributes':
        'description': >
            You can add additional information.
        'label': 'Additional information and/or screenshots'
        'placeholder': >
            Anything that can help to solve the problem.
    'id': 'additional'
    'type': 'textarea'
    'validations':
        'required': false
'name': 'Bug'
