'name': 'Check Potential Duplicates'
'on':
    'issues':
        'types':
          - 'opened'
    'workflow_dispatch':
'jobs':
    'checkduplicate':
        'runs-on': 'ubuntu-latest'
        'steps':
          - 'uses': 'wow-actions/potential-duplicates@v1'
            'with':
                'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}'
                'state': 'all'
                'threshold': 0.6
                'comment': |
                    Potential duplicates: {{#issues}}
                     *  [#{{ number }}] {{ title }} ({{ accuracy }}%)
                    {{/issues}}
    add-assigness:
        runs-on: ubuntu-latest
        steps:
          - name: Add assigness
            uses: actions-cool/issues-helper@v3
            with:
              actions: 'add-assignees'
              token: ${{ secrets.GITHUB_TOKEN }}
              assignees: 'txyyddss,reallapt'
