name: Issue Reply

on:
  issues:
    types: ["labeled"]

jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: More information needed
        if: github.event.label.name == 'need-more-info'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We need more information or futher investigation. Please provide more info or possible guesses/solution for the issue.
  wontfix:
    runs-on: ubuntu-latest
    steps:
      - name: Not being fixed
        if: github.event.label.name == 'wontfix'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          
