name: Fetch Completed Issues

on:
  workflow_dispatch:
    inputs:
      target_date:
        description: '目标日期 (YYYY-MM-DD)'
        required: true
        type: string

jobs:
  fetch-completed:
    runs-on: ubuntu-latest
    steps:
      - name: 查询已关闭的Issues
        env:
          TARGET_DATE: ${{ inputs.target_date }}
        run: |
          # 转换日期格式并调用API
          TARGET_ISO="${TARGET_DATE}T00:00:00Z"
          echo "查询日期: $TARGET_ISO"
          
          # 使用GitHub Search API查找符合的issues
          response=$(curl -sL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/search/issues?q=repo:${{ github.repository }}+is:issue+is:closed+closed:>=${TARGET_ISO}")
          
          # 提取结果并保存为JSON文件
          echo "$response" | jq '.items' > completed_issues.json
          echo "找到 $(echo "$response" | jq '.items | length') 个符合条件的issue"
          
          # 输出结果供后续步骤使用
          echo "ISSUES_JSON=$(jq -c '.' completed_issues.json)" >> $GITHUB_OUTPUT

      - name: 显示结果
        run: |
          if [ -s completed_issues.json ]; then
            echo "### 发现的已关闭Issues" >> $GITHUB_STEP_SUMMARY
            jq -r '.[] | "- #\(.number) \(.title) (关闭于: \(.closed_at))"' completed_issues.json >> $GITHUB_STEP_SUMMARY
          else
            echo "没有找到符合的issues" >> $GITHUB_STEP_SUMMARY
          fi